deform/src/main.rs
gfx_cube/src/main.rs
image/src/main.rs
music/src/main.rs
paint/src/main.rs
user_input/src/main.rs

* Replaced piston-current with piston-quack
Problems with https://github.com/PistonDevelopers/sprite/issues/57 and
https://github.com/PistonDevelopers/event/issues/305

Upgraded some examples

---

gfx_cube/Cargo.toml
gfx_cube/src/main.rs
user_input/Cargo.toml
user_input/src/main.rs

It looks like sdl_mixer is broken upstream. user_input seems to have odd graphical artifacts when I run it but at least it builds :)

Fixing gfx_cube and user_input examples

---

.travis.yml
deform/src/main.rs
gfx_cube/src/main.rs
paint/src/main.rs
sprite/src/main.rs
user_input/src/main.rs

Fix Travis: fix glfw build, remove music example, add deform example.
Fix errors and warnings in examples.

Fix various things

---

user_input/Cargo.toml
user_input/src/main.rs

Can change back-end by editing the Cargo.toml

Updated user_input to support multiple back-ends

---

deform/src/main.rs

Will break Travis CI because rust-sdl2 isn't updated.

Upgraded "deform" example to latest piston-graphics

---

gfx_cube/src/main.rs
sprite/src/main.rs

DON'T MERGE THIS until `gl-rs` and `gfx_gl` updated.

Update to latest gfx and graphics

---

user_input/Cargo.toml
user_input/src/main.rs

To test the Glutin window back-end.

Added drawing of cursor position to "user_input" example

---

sprite/src/main.rs

Fix when broken by https://github.com/PistonDevelopers/sprite/pull/76
:)

fixed example to pass uuid by ref

---

gfx_cube/src/main.rs

Self merge after Travis says ok.

Upgrade gfx_cube example to latest sdl2_window

---

sprite/src/main.rs

Remove references so that they can be copied.

fix fallout of Uuid becoming Copy

---

gfx_cube/Cargo.toml
gfx_cube/src/main.rs

Change gfx_cube example to use glfw_window

---

gfx_cube/Cargo.toml
gfx_cube/src/main.rs

Use Glutin in "gfx_cube"

---

gfx_cube/Cargo.toml
gfx_cube/src/main.rs

* Switched to sdl2 since mouse relative is not supported on glutin yet.

Updated "gfx_cube" example

---

gfx_cube/Cargo.toml
gfx_cube/src/main.rs

Wait for https://github.com/PistonDevelopers/piston_window/pull/41

Upgraded to piston_window 0.2.0

---

Cargo.toml
src/texture_swap.rs

This will be used to benchmark swapping of textures.

Added `texture_swap`

---

user_input/Cargo.toml
user_input/src/main.rs

See https://github.com/PistonDevelopers/piston-examples/issues/310

Added visual axis values to "user_input" example

---

README.md
src/hello_world.rs

I lost an embarrassing amount of time to this, so hopefully I can save others from my fate.  The README is the first thing a lot of people will see too.

Add an additional piece of information to the README

---

assets/cube_120.glslv
assets/cube_150.glslv

Closes https://github.com/PistonDevelopers/piston-examples/issues/340

Fixed "cube" example

---

Cargo.toml
src/multi_window.rs
src/paint.rs
src/texture_swap.rs

- Removed unused imports from “src/paint.rs” and “src/texture_swap.rs”

Added multi-window example

---

src/cube.rs

Implement chriscamacho's suggestion for cube indexes

---

README.md

Closes https://github.com/PistonDevelopers/piston-examples/issues/385

Rust nightly is no longer required

---

src/image.rs
src/paint.rs

See https://github.com/PistonDevelopers/piston/issues/1213

Use `G2dTexture` in examples

---

examples/hello_world.rs

I noticed in the Hello World example the colors were kinda ugly, so I changed the colors to something a little more pleasing to the eye. The text is black and the background is white.

Changed hello_world colors

---

Cargo.toml
examples/snake.rs

Added a simple snake game to the examples
Added some dependencies to make the game work
Updated rand from 0.6.0 to 0.8.5 to make the game work

Add snake example
